# Generated by Django 4.1 on 2024-04-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('BrandID', models.IntegerField(primary_key=True, serialize=False)),
                ('BrandName', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.TextField(null=True)),
                ('CategoryID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.TextField(null=True)),
                ('ProductName', models.CharField(max_length=255)),
                ('BrandDesc', models.TextField(null=True)),
                ('ProductSize', models.TextField(null=True)),
                ('Currency', models.TextField(null=True)),
                ('SalePrice', models.IntegerField(null=True)),
                ('Discount', models.TextField(null=True)),
                ('BrandID', models.IntegerField(null=True)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, to='shopping.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category'),
        ),
    ]
