# Generated by Django 4.1 on 2024-04-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_sell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
    ]
