# Generated by Django 4.1 on 2024-04-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
